### ISSUE TITLE
Le promesse elettorali di #CristianaAvenali su sviluppo sostenibile 

### ISSUE THREAD

**Issue by politicacorr** [HackForItaly/politicamentecorretto_data#101]
<pre><yamldata>Nome: 'Cristiana Avenali'
data: 25/01/2018
Nome fonte: 'Blog Cristiana Avenali'
urlfonte: 'http://www.cristianaavenali.it/nicola-zingaretti-continuare-lavoro-nel-lazio-apertura-della-mia-campagna-elettorale-27-01-2018/'
dichiarazione: '"Alle prossime elezioni regionali ho deciso di candidarmi per il rinnovo del Consiglio regionale del Lazio. È una sfida avvincente ed importante per poter proseguire il lavoro svolto in questi cinque anni di governo, con l’impegno di continuare a fare del Lazio una Regione migliore. Per questo supporto con piacere e convinzione la candidatura di Nicola Zingaretti Presidente, presentandomi nella lista del PD per l’elezione del Consiglio regionale”, dichiara in una nota Cristiana Avenali,  consigliera regionale del Lazio. “Sono certa che quella tracciata sino ad oggi sia la strada giusta da seguire: perché credo che ambiente, diritti ed occupazione siano fondamentali per rilanciare l’economia e migliorare la qualità della vita di ognuno di noi, e sono sicura che nei prossimi cinque anni potremo realizzare fino in fondo un modello di sviluppo sostenibile."'
id: '24504642'
unapromessaID: ''
</yamldata></pre>

**Comment by cristigalas** [comment]
Questa promessa, a cui ho tolto un po' di discorsi su quel che ha fatto la giunta Zingaretti, rimane secondo me troppo generica e non l'accetterei. @favoeva che dici?

**Comment by favoeva** [comment]
sì, direi di non pubblicarla .
