### ISSUE TITLE
Le promesse elettorali di Emanuele Fiano

### ISSUE THREAD

**Issue by politicacorr** [HackForItaly/politicamentecorretto_data#104]
<pre><yamldata>Nome: 'Emanuele Fiano'
data: 25/01/2018
Nome fonte: 'https://twitter.com/emanuelefiano'
urlfonte: 'https://twitter.com/emanuelefiano/status/956448952605401088'
dichiarazione: '"""Qualcuno ha già cercato di fare campagna elettorale sui morti di #Pioltello. Mi dispiace io non sarò mai all’altezza del tuo cinismo @matteosalvinimi e ne sono ben contento. Cordoglio per i morti, la magistratura accerti le responsabilità. Non si può morire per andare a lavorare."""'
id: '24522731'
unapromessaID: ''
</yamldata></pre>

**Comment by cristigalas** [comment]
Questa non l'accetterei, non è una promessa.
