### ISSUE TITLE
Le promesse elettorali di Graziano Delrio

### ISSUE THREAD

**Issue by politicacorr** [HackForItaly/politicamentecorretto_data#105]
<pre><yamldata>Nome: 'Graziano Delrio'
data: 25/01/2018
Nome fonte: 'ANSA.it Lombardia'
urlfonte: 'http://milano.corriere.it/notizie/cronaca/18_gennaio_25/treno-deragliato-pioltello-delrio-una-linea-le-piu-monitorate-246c1634-01ee-11e8-9ff2-341a2fe0297c.shtml'
dichiarazione: '"Delrio, su Pioltello vogliamo verità : attivata Commissione ministeriale d''inchiesta ""Il sistema ferroviario italiano è certamente uno dei più sicuri al mondo ma vogliamo la verità, la si accerti rapidamente, perché è inaccettabile morire mentre  si va al lavoro""  ""Oggi è il momento del rispetto e del cordoglio, della vicinanza alle famiglie. Ho sentito dire molte volte in queste ore del tema degli  investimenti sulla sicurezza: vi posso garantire che gli investimenti in sicurezza sono aumentati del 340% negli ultimi tre anni. È la nostra priorità in particolar modo nelle reti dei pendolari"". ""Oggi è il momento del rispetto e del cordoglio, della vicinanza alle famiglie. Ho sentito dire molte volte in queste ore del tema degli investimenti sulla sicurezza: vi posso garantire che gli investimenti in sicurezza sono aumentati del 340% negli ultimi tre anni. È la nostra priorità in  particolar modo nelle reti dei pendolari"".Con il Prefetto Luciana Lamorgese, Delrio ha ringraziato la macchina dei soccorsi per ""l''elevata efficienza: in meno di 20''venti minuti sono arrivati sul posto""."'
id: '24524034'
unapromessaID: ''
</yamldata></pre>

**Comment by cristigalas** [comment]
Non mi pare una promessa elettorale, @favoeva che dici chiudiamo?
