### ISSUE TITLE
Le promesse elettorali di Stefano Parisi

### ISSUE THREAD

**Issue by politicacorr** [HackForItaly/politicamentecorretto_data#117]
<pre><yamldata>Nome: 'Stefano Parisi'
data: 26/01/2018
Nome fonte: 'Energie per L''Italia (canale youtube)'
urlfonte: 'https://www.youtube.com/watch?time_continue=62&v=l3F3IAw0urU'
dichiarazione: 'Consob e Sky stanno abbandonando Roma, io sono qua per far tornare Roma a essere il centro non solo burocratico, ma dello sviluppo economico del paese.'
id: '24576821'
unapromessaID: ''
</yamldata></pre>

**Comment by cristigalas** [comment]
@favoeva che dici accettiamo? Mi pare molto generica... Comunque semmai potremmo pubblicarla col titolo "promesse elettorali su Roma capitale dello sviluppo economico".

**Comment by favoeva** [comment]
di fatto è una sorta di duplicato della #125 pubblicata, quindi chiudo
