### ISSUE TITLE
Le promesse elettorali di Stefano parisi

### ISSUE THREAD

**Issue by politicacorr** [HackForItaly/politicamentecorretto_data#119]
<pre><yamldata>Nome: 'Stefano parisi'
data: 28/01/2018
Nome fonte: 'Twitter @s_parisi'
urlfonte: 'https://twitter.com/s_parisi/status/957596269047926784'
dichiarazione: '#Cultura L''Italia non può vivere solo di rendita: deve tornare ad essere luogo di produzione culturale. Dobbiamo valorizzare e incentivare fattivamente i nostri talenti, i nostri giovani, il nostro genio. Ecco la nuova politica culturale del #centrodestra https://t.co/cxpREvPHJR'
id: '24609850'
unapromessaID: ''
</yamldata></pre>

**Comment by cristigalas** [comment]
Mi sembra una proposta troppo vaga, fatta solo di slogan. Non accetterei.

**Comment by favoeva** [comment]
mi sembra interessante il rif. a "incentivare fattivamente produzione culturale"... inoltre abbiamo poco o nulla in categoria arte e cultura :(
