### ISSUE TITLE
Le promesse elettorali di Lucia Annibali

### ISSUE THREAD

**Issue by politicacorr** [HackForItaly/politicamentecorretto_data#128]
<pre><yamldata>Nome: 'Lucia Annibali'
data: 29/01/2018
Nome fonte: 'Partito Democratico'
urlfonte: 'https://www.facebook.com/partitodemocratico.it/videos/10155609295881896/'
dichiarazione: 'Lucia Annibali annuncia il programma di aiuto per le donne vittime di violenza'
id: '24640937'
unapromessaID: ''
</yamldata></pre>

**Comment by favoeva** [comment]
sono le linee guida del dip. Pari Opportunità della Presidenza del Consiglio. Non è una promessa elettorale
