### ISSUE TITLE
Le promesse elettorali di Programma Partito Democratico

### ISSUE THREAD

**Issue by politicacorr** [HackForItaly/politicamentecorretto_data#161]
<pre><yamldata>Nome: 'Programma Partito Democratico'
data: 06/02/2018
Nome fonte: 'PD'
urlfonte: 'https://www.facebook.com/matteorenziufficiale/videos/10155631529519915/'
dichiarazione: 'La presentazione del #programmaPD: 100 impegni raggiunti, 100 obiettivi che vogliamo raggiungere.'
id: '24912182'
unapromessaID: ''
</yamldata></pre>

**Comment by cristigalas** [comment]
Non è una promessa ma la presentazione del programma elettorale Pd.
