### ISSUE TITLE
Le promesse elettorali di #Berlusconi Silvio

### ISSUE THREAD

**Issue by politicacorr** [HackForItaly/politicamentecorretto_data#28]
<pre><yamldata>Nome: '#Berlusconi Silvio'
data: 19/01/2018
Nome fonte: 'La Stampa.it'
urlfonte: 'http://www.lastampa.it/2018/01/19/italia/politica/berlusconi-via-le-tasse-su-casa-auto-e-successioni-cKo2R0d23Sx6E4lvMBKRqK/pagina.html'
dichiarazione: '«non ci saranno più tasse sulla prima casa, neppure sull’auto, non saranno tassate le successioni né le donazioni, elimineremo l’Irap: questa flat tax è una rivoluzione globale, che porterà economia a crescere e a creare posti di lavoro». Nel programma del centrodestra, «non c’è soltanto questa rivoluzione fiscale molto conveniente ma ci sarà anche il fatto che se per esempio un cittadino italiano imputato viene dichiarato innocente, i pm non possono più richiamarlo in appello, rovinandogli definitivamente la vita», ha detto l’ex premier. «Vi sarà poi un cambiamento nella Costituzione - ha concluso - che non consentirà il cambio di partito fra i parlamentari».     «Per me rispettare le promesse è la prima moralità della politica. Io ho sempre mantenute le mie promesse», ha sottolineato ancora. «Sono soddisfatto, per un programma lungamente approfondito, che io ho cominciato a preparare, tempo fa, convocando gli elettori nella mia università», ha detto parlando della firma a Palazzo Grazioli con Salvini e Meloni, sul programma del centrodestra.'
id: '24270269'
</yamldata></pre>

**Comment by favoeva** [comment]
chiudo perchè doppia
