### ISSUE TITLE
Le promesse elettorali di Zingaretti

### ISSUE THREAD

**Issue by politicacorr** [HackForItaly/politicamentecorretto_data#60]
<pre><yamldata>Nome: 'Zingaretti'
data: 21/01/2018
Nome fonte: ''
urlfonte: ''
dichiarazione: 'volevo segnalare che questa dichiarazione non dovrebbe essere collegata a LeU  https://www.unapromessa.it/promessa/22/'
id: '24329647'
unapromessaID: ''
</yamldata></pre>

**Comment by cristigalas** [comment]
Grazie! Corretta!
