### ISSUE TITLE
Le promesse elettorali di Maurizio #Lupi #Udc per il commercio: azzerare le tasse ai negozi di periferia

### ISSUE THREAD

**Issue by politicacorr** [HackForItaly/politicamentecorretto_data#88]
<pre><yamldata>Nome: 'Maurizio Lupi'
data: 24/01/2018
Nome fonte: 'Profilo Twitter'
urlfonte: 'https://twitter.com/Maurizio_Lupi/status/954004701393104896'
dichiarazione: 'I negozi di periferia vanno intesi anche come presidi sociali del territorio. La presenza di un’attività commerciale in zone difficili delle nostre città è un valore da difendere e da valorizzare, la nostra proposta è prevedere per loro #zerotasse #sicurezzaperiferie'
id: '24457102'
unapromessaID: 'Q3852636'
</yamldata></pre>

**Comment by cristigalas** [comment]
Già presente, vedi #50.
