### ISSUE TITLE
Le promesse elettorali di AgCom, l’Autorità per le Garanzie nelle Comunicazioni

### ISSUE THREAD

**Issue by politicacorr** [HackForItaly/politicamentecorretto_data#99]
<pre><yamldata>Nome: 'AgCom, l’Autorità per le Garanzie nelle Comunicazioni'
data: 25/01/2018
Nome fonte: 'Democratica'
urlfonte: 'https://www.democratica.com/focus/elezioni-par-condicio-agcom-richiamo-la7/'
dichiarazione: 'Disparità nell’informazione politica e violazione della par condicio, a danno quasi esclusivo del Pd e del centrosinistra.  È quanto emerge dal richiamo per violazione della par condicio che l’AgCom, l’Autorità per le Garanzie nelle Comunicazioni, ha fatto arrivare all’indirizzo di ben cinque testate. Tra queste, un richiamo “forte” è stato indirizzato all’emittente La7.  Le testate ‘richiamate’ da AgCom Il periodo preso in esame è quello che va dal 15 al 21 di gennaio e, scendendo nel dettaglio del comunicato diffuso dall’Autorità, si legge che il Consiglio di AgCom ha deliberato “un forte richiamo all’emittente La7 in relazione al tempo di parola e al tempo di notizia dedicato, specie nelle edizioni principali, a M5S e Lega a svantaggio di altri partiti, segnatamente, PD e Forza Italia, un forte richiamo a Tg4 e a Studio Aperto in relazione all’elevato tempo di notizia fruito da FI a svantaggio delle altre forze politiche, in particolare nelle edizioni principali, un richiamo a Skytg24 in relazione all’eccessivo tempo di parola, riflesso anche nel tempo di notizia, destinato a M5S, LeU e Lega a detrimento delle altre forze politiche, e un richiamo a Rainews per lo squilibrio registrato nei tempi di parola a favore di LeU e a detrimento del PD”.    Penalizzato il Pd In pratica, nell’intero arco dell’offerta informativa in Tv non c’è emittente o quasi che non si sia fatta notare dall’Autorità vigilante in materia di par condicio. Ma mentre lo squilibrio ‘a favore’ pare ben distribuito, con di volta in volta favoriti, nel tempo concesso, M5S, Lega, Forza Italia o LeU, il tratto comune è lo squilibrio a sfavore, che in tutti i casi ha visto penalizzato il Pd e il centrosinistra.  L’AgCom ha invitato le emittenti a porre rimedio entro la prossima rilevazione settimanale, che si concluderà il 28 gennaio.'
id: '24491916'
unapromessaID: ''
</yamldata></pre>

**Comment by cristigalas** [comment]
Questa non mi pare una promessa elettorale, non l'accetterei...

**Comment by favoeva** [comment]
sì sì qui l'argomento è la par condicio... potremmo forse farci un post o un tweet

**Comment by cristigalas** [comment]
Vado io con il tweet e pensi tu eventualmente a post su Fb?
